feat: logica e implentacion Airspeed indicator
luisfezm/proyectoCessna152-construccion pull request #42
Opened 2023-06-20 02:32 UTC by Diego-Mancilla

Componente: Airspeed indicator 
-Diego Mancilla
-Nicolas Iturra

2023-06-20 06:58 UTC, lucckkas requested changes
los pedales no son aceleradores, el acelerador es una palanca llamada throttle

2023-06-20 22:51 UTC, Diego-Mancilla commented
Cambio de uso de Pedal a tecla de teclado

2023-06-21 07:17 UTC, lucckkas requested changes
no veo una variable que me permita saber mi velocidad en cada instante (pensando en que otros componentes lo necesitaran) me parece importante tenerla

2023-06-21 15:48 UTC, Diego-Mancilla commented
variable integrada

2023-06-21 22:15 UTC, lucckkas requested changes
la variable actua como un limite de velocidad, lo que esperaba es una que me guarde a donde esta apuntando la aguja del indicador en cada momento

2023-06-26 01:10 UTC, closed without merging

2023-06-26 01:10 UTC, luisfezm commented
Se iniciará un nuevo pull request desde sprint2-mancilla a sprint3 ya que implementará los cambios en esta nueva semana